/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p17.reto4.vista;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import utp.misiontic2022.c2.p17.reto4.controlador.ControladorRequerimientos;

/**
 *
 * @author juter
 */
public class menu extends javax.swing.JFrame {
    private final ControladorRequerimientos controlador;
    private ConsultaTM consultaTM;
    private ConsultaTM2 consultaTM2;
    private ConsultaTM3 consultaTM3;

    /**
     * Creates new form menu
     */
    public menu() {
        controlador = new ControladorRequerimientos();
        initComponents();
        CargarConsulta1();
        CargarConsulta2();
        CargarConsulta3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JTabbedPane();
        pConsulta1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTablaC1 = new javax.swing.JTable();
        pConsulta2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tTablaC2 = new javax.swing.JTable();
        pConsulta3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTablaC3 = new javax.swing.JTable();
        mMenuapp = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mExit = new javax.swing.JMenuItem();
        mWindows = new javax.swing.JMenu();
        mConsulta1 = new javax.swing.JMenuItem();
        mConsulta2 = new javax.swing.JMenuItem();
        mConsulta3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultas_ProyectoConstruccion");

        pConsulta1.setLayout(new java.awt.BorderLayout());

        tTablaC1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tTablaC1);

        pConsulta1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pPrincipal.addTab("consulta 1", pConsulta1);

        pConsulta2.setLayout(new java.awt.BorderLayout());

        tTablaC2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tTablaC2);

        pConsulta2.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pPrincipal.addTab("consulta 2", pConsulta2);

        pConsulta3.setLayout(new java.awt.BorderLayout());

        tTablaC3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tTablaC3);

        pConsulta3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pPrincipal.addTab("consulta 3", pConsulta3);

        getContentPane().add(pPrincipal, java.awt.BorderLayout.CENTER);

        mFile.setText("file");

        mExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mExit.setText("Exit");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        mFile.add(mExit);

        mMenuapp.add(mFile);

        mWindows.setText("windows");

        mConsulta1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mConsulta1.setText("consulta 1");
        mConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsulta1ActionPerformed(evt);
            }
        });
        mWindows.add(mConsulta1);

        mConsulta2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mConsulta2.setText("consulta 2");
        mConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsulta2ActionPerformed(evt);
            }
        });
        mWindows.add(mConsulta2);

        mConsulta3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mConsulta3.setText("Consulta 3");
        mConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsulta3ActionPerformed(evt);
            }
        });
        mWindows.add(mConsulta3);

        mMenuapp.add(mWindows);

        setJMenuBar(mMenuapp);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void CargarConsulta1(){
        try {
            var requerimientos1 = controlador.consultarRequerimiento1();
            consultaTM = new ConsultaTM(requerimientos1);
            tTablaC1.setModel(consultaTM);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }
    private void CargarConsulta2(){
        try {
            var requerimientos2 = controlador.consultarRequerimiento2();
            consultaTM2 = new ConsultaTM2(requerimientos2);
            tTablaC2.setModel(consultaTM2);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }
     private void CargarConsulta3(){
        try {
            var requerimientos3 = controlador.consultarRequerimiento3();
            consultaTM3 = new ConsultaTM3(requerimientos3);
            tTablaC3.setModel(consultaTM3);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }
    private void mConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsulta1ActionPerformed
        pPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_mConsulta1ActionPerformed

    private void mConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsulta2ActionPerformed
        pPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_mConsulta2ActionPerformed

    private void mConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsulta3ActionPerformed
        pPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_mConsulta3ActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Desea salir?", getTitle(),
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                dispose();
          
        }
    }//GEN-LAST:event_mExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenuItem mConsulta1;
    private javax.swing.JMenuItem mConsulta2;
    private javax.swing.JMenuItem mConsulta3;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuBar mMenuapp;
    private javax.swing.JMenu mWindows;
    private javax.swing.JPanel pConsulta1;
    private javax.swing.JPanel pConsulta2;
    private javax.swing.JPanel pConsulta3;
    private javax.swing.JTabbedPane pPrincipal;
    private javax.swing.JTable tTablaC1;
    private javax.swing.JTable tTablaC2;
    private javax.swing.JTable tTablaC3;
    // End of variables declaration//GEN-END:variables
}
